apiVersion: v1
kind: Pod
metadata:
  name: producer-pod
  labels:
    app: producer
spec:
  containers:
  - name: producer
    image: jqayyum/producer
    env:
      - name: DATASOURCE_HOST
        value: h2-service
